### ISSUE TITLE
Community actions brain storm

### ISSUE THREAD

**Issue by eprice555** [ProgramEquity/april-hackathon#2]
We want to brainstorm idea's on community actions we can add to our upcoming curriculum. Feel free to provide feedback as a comment.

This issue is for brain storming our current issues for EPIC 3 of the 2024 hackpod. Here is the previous issues/information we used last cohort. Our goal is to improve upon our current issues and update them as needed. 

- [ ] [Update integration tests to not make a real API calls](https://github.com/OpenSourceFellows/amplify/issues/296)
- [ ] [Are You Awake Yet Action](https://github.com/OpenSourceFellows/amplify/issues/623)
- [ ] [Spellcheck Action](https://github.com/OpenSourceFellows/amplify/issues/626)
- [ ] [Calendar Notification Action](https://github.com/OpenSourceFellows/map-dashboard/issues/37)
- [ ] [[Architecture] Labeler Action](https://github.com/OpenSourceFellows/amplify/issues/625)
- [ ] [[Architecture] GitEmote - Comment Action](https://github.com/OpenSourceFellows/amplify/issues/630)
- [ ] [[Documentation] Convert legacy issue templates to web forms](https://github.com/OpenSourceFellows/amplify/issues/355)
- [ ] [Create Labeler GitHub Action Workflow](https://github.com/OpenSourceFellows/amplify/pull/556)
- [ ] [Create Unit Tests GitHub Action Workflow](https://github.com/OpenSourceFellows/amplify/pull/551)
- [ ] [Hack Pod: Enhance Dev Experience via Codespaces + Secure Workflows](https://github.com/OpenSourceFellows/amplify/issues/19)
- [ ] [Test Reporting on CI](https://github.com/OpenSourceFellows/amplify/pull/153)
- [ ] [Batch: Setting up Mayhem API](https://github.com/OpenSourceFellows/amplify/issues/130)
- [ ] [Epic 2: Securing current workflows](https://github.com/OpenSourceFellows/amplify/issues/158)
- [ ] [Task: Get ESLint + Prettier working for Vue files](https://github.com/OpenSourceFellows/amplify/issues/89)

Resources
- [Section on Test Driven Development + Workshop](https://www.notion.so/programequity/Test-Driven-Development-With-Stripe-40de27d593d748e08fdf47296807eab5?pvs=4)
- Our [current tests ](https://github.com/ProgramEquity/amplify/tree/main/server/__tests__/integration)
- How to [mock tests ](https://jestjs.io/docs/manual-mocks)
- Deployment modeling  
  - [AWS](https://aws.amazon.com/blogs/devops/integrating-with-github-actions-ci-cd-pipeline-to-deploy-a-web-app-to-amazon-ec2/)
  - [Azure](https://learn.microsoft.com/en-us/azure/architecture)
  - [GCP](https://cloud.google.com/deployment-manager/docs)

### 3. Finalizing (Actions for secure workflows and vulnerability mitigations) @eprice555 @rcmtcristian 
Resources:
- [Security hardening of Actions](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions)
- [Audit of our OSS workflow](https://github.com/ProgramEquity/amplify/discussions/61)
- [About code scanning](https://codeql.github.com/docs/) (CodeQL)

**Comment by eprice555** [comment]
Based on today's Mentor meetup will be making minor changes to the packet manager by switching to [PNMP](https://github.com/pnpm/pnpm). This will need to be addressed for the upcoming cohort, cc @DietBepis1 @rcmtcristian
